# Generated by Django 3.1.7 on 2021-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
